version: '3'

services:
  frontend:
    build:
      context: ./console-dir/geojson-console
    ports:
      - "3000:80"

  backend:
    build:
      context: ./jsserver
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
