# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Install dependencies
COPY . /app/

RUN npm install

# Copy the rest of the application
COPY . .

# Expose port 3001 (or your server port)
EXPOSE 3001

# Start the server
CMD ["node", "spatialintersection.js"]
